import { adminPeriod, loadAdminGrowthMetrics } from "@/lib/admin-growth-metrics";
import { DataNotice, GrowthHeader, UpgradeReady } from "../_growth-ui";
import { Kpi } from "../_ui";
import { CircleDollarSign, CreditCard, ReceiptText, TrendingUp } from "lucide-react";

export const dynamic = "force-dynamic";
export const metadata = { title: "Admin · Revenue", robots: { index: false } };
export default async function RevenuePage({ searchParams }: { searchParams?: Promise<{ range?: string; from?: string; to?: string }> }) {
 const query=(await searchParams)??{}; const m=await loadAdminGrowthMetrics(adminPeriod(query)); const activePro=m.activePaid.filter(u=>u.tier==="pro").length; const activePlus=m.activePaid.filter(u=>u.tier==="pro_plus").length; const checkout=new Set(m.events.filter(e=>e.name==="checkout_started").map(e=>e.userId||e.sessionId).filter(Boolean)).size; const purchases=new Set(m.events.filter(e=>e.name==="purchase_completed").map(e=>e.userId||e.sessionId).filter(Boolean)).size;
 return <div className="adm-page"><GrowthHeader title="Revenue" sub="Abbonamenti, checkout e priorità di conversione." active="/admin/revenue" query={query}/><div style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:12}}><Kpi label="MRR attuale" value={`€${m.mrr.toLocaleString("it-IT",{maximumFractionDigits:2})}`} sub="Solo subscription Stripe attive" tone="good" icon={<CircleDollarSign size={15}/>}/><Kpi label="Paganti attivi" value={m.activePaid.length} sub={`${activePro} Pro · ${activePlus} Pro+`} icon={<CreditCard size={15}/>}/><Kpi label="Checkout avviati" value={checkout} sub={m.period.label} icon={<ReceiptText size={15}/>}/><Kpi label="Pagamenti riusciti" value={purchases} sub="Eventi payment success nel periodo" icon={<TrendingUp size={15}/>}/></div><div style={{display:"grid",gridTemplateColumns:"minmax(0,1.1fr) minmax(340px,1fr)",gap:12}}><section className="adm-card"><div className="adm-card-head"><div><div className="adm-card-title">Funnel abbonamento</div><div className="adm-card-sub">Misura gli eventi effettivamente registrati nel periodo.</div></div></div>{[["Checkout avviato",checkout],["Pagamento riuscito",purchases],["Abbonamenti attivi ora",m.activePaid.length]].map(([label,value],i)=><div key={String(label)} className="adm-tr" style={{gridTemplateColumns:"160px 1fr 48px"}}><span>{label}</span><span style={{height:8,background:"var(--bg-sunken)",borderRadius:99,overflow:"hidden"}}><span style={{display:"block",height:"100%",width:`${checkout?Number(value)/checkout*100:0}%`,background:i===2?"#fbbf24":"hsl(var(--primary))"}}/></span><b className="adm-num" style={{textAlign:"right"}}>{value}</b></div>)}</section><UpgradeReady metrics={m}/></div><DataNotice>ARPU, churn, MRR history, cohort retention, upgrade/downgrade e payment failed richiedono eventi di fatturazione versionati. Sono intenzionalmente indicati come in raccolta, non dedotti dal piano attuale.</DataNotice></div>;
}
