/**
 * Curated list di aziende che usano Greenhouse / Lever / Workable con
 * focus su Italia / Europa. Da estendere nel tempo.
 *
 * Criterio: aziende tech/SaaS/fintech con job listing IT o EU + ATS noto.
 */

export interface AtsCompany {
  slug: string; // slug usato dall'ATS (boards.greenhouse.io/<slug>)
  name: string; // nome user-facing
  country?: string;
}

export const GREENHOUSE_COMPANIES: AtsCompany[] = [
  // Italia
  { slug: "satispay", name: "Satispay", country: "IT" },
  { slug: "bendingspoons", name: "Bending Spoons", country: "IT" },
  { slug: "scalapay", name: "Scalapay", country: "IT" },
  { slug: "casavo", name: "Casavo", country: "IT" },
  { slug: "moneyfarm", name: "MoneyFarm", country: "IT" },
  { slug: "docebo", name: "Docebo", country: "IT" },
  { slug: "everli", name: "Everli", country: "IT" },
  { slug: "lastminutecom", name: "Lastminute.com", country: "IT" },
  { slug: "treatwell", name: "Treatwell", country: "IT" },
  { slug: "italist", name: "Italist", country: "IT" },
  { slug: "young", name: "Young Platform", country: "IT" },
  { slug: "growens", name: "Growens", country: "IT" },
  { slug: "jethr", name: "Jet HR", country: "IT" },
  { slug: "cleafy", name: "Cleafy", country: "IT" },
  { slug: "prima", name: "Prima Assicurazioni", country: "IT" },
  { slug: "wonderflow", name: "Wonderflow", country: "IT" },
  { slug: "moltiply", name: "Moltiply", country: "IT" },
  { slug: "faire", name: "Faire", country: "IT" },
  { slug: "brunello", name: "Brunello Cucinelli", country: "IT" },
  { slug: "nexiitaly", name: "Nexi Italy", country: "IT" },
  // Italia — nuovi (aggiunti per pool Milano)
  { slug: "nexi", name: "Nexi", country: "IT" },
  { slug: "brumbrum", name: "BrumBrum", country: "IT" },
  { slug: "sorgenia", name: "Sorgenia", country: "IT" },
  { slug: "illimity", name: "Illimity", country: "IT" },
  { slug: "d-orbit", name: "D-Orbit", country: "IT" },
  { slug: "dorbit", name: "D-Orbit (alt)", country: "IT" },
  { slug: "moltiplygroup", name: "Moltiply Group", country: "IT" },
  { slug: "facile", name: "Facile.it", country: "IT" },
  { slug: "facileit", name: "Facile.it (alt)", country: "IT" },
  { slug: "iconplc", name: "ICON plc (Italia)", country: "IT" },
  { slug: "velascogroup", name: "Velasco Group", country: "IT" },
  { slug: "mediobanca", name: "Mediobanca", country: "IT" },
  { slug: "unipolsai", name: "UnipolSai", country: "IT" },
  { slug: "generali", name: "Generali", country: "IT" },
  { slug: "talentgarden", name: "Talent Garden", country: "IT" },
  { slug: "cortilia", name: "Cortilia", country: "IT" },
  { slug: "yolo", name: "Yolo Group", country: "IT" },
  { slug: "young-platform", name: "Young Platform (alt)", country: "IT" },
  { slug: "aidentive", name: "Aidentive", country: "IT" },
  { slug: "wavy", name: "Wavy", country: "IT" },
  { slug: "tannico", name: "Tannico", country: "IT" },
  { slug: "freedome", name: "Freedome", country: "IT" },
  { slug: "axieme", name: "Axieme", country: "IT" },
  { slug: "bonusx", name: "BonusX", country: "IT" },
  { slug: "vicini", name: "Vicini", country: "IT" },

  // EU ampio (hanno spesso roles remote EU / Italia)
  { slug: "airbnb", name: "Airbnb" },
  { slug: "stripe", name: "Stripe" },
  { slug: "spotify", name: "Spotify" },
  { slug: "getyourguide", name: "GetYourGuide" },
  { slug: "n26", name: "N26" },
  { slug: "revolut", name: "Revolut" },
  { slug: "remote", name: "Remote" },
  { slug: "deel", name: "Deel" },
  { slug: "miro", name: "Miro" },
  { slug: "hopin", name: "Hopin" },
  { slug: "notion", name: "Notion" },
  { slug: "canva", name: "Canva" },
  { slug: "intercom", name: "Intercom" },
  { slug: "algolia", name: "Algolia" },
  { slug: "mercari", name: "Mercari" },
  { slug: "typeform", name: "Typeform" },
  { slug: "personio", name: "Personio" },
  { slug: "sumup", name: "SumUp" },
  { slug: "tandem", name: "Tandem" },
  { slug: "qonto", name: "Qonto" },
  { slug: "pennylane", name: "Pennylane" },
  { slug: "alan", name: "Alan" },
  { slug: "doctolib", name: "Doctolib" },
  { slug: "backmarket", name: "Back Market" },
  { slug: "blablacar", name: "BlaBlaCar" },
  { slug: "contentful", name: "Contentful" },
  { slug: "wayflyer", name: "Wayflyer" },
  { slug: "ovhcloud", name: "OVHcloud" },
  // Big tech + scaleup espanse — molte hanno HQ EU + remote
  { slug: "shopify", name: "Shopify" },
  { slug: "duolingo", name: "Duolingo" },
  { slug: "twilio", name: "Twilio" },
  { slug: "snowflake", name: "Snowflake" },
  { slug: "datadog", name: "Datadog" },
  { slug: "mongodb", name: "MongoDB" },
  { slug: "elastic", name: "Elastic" },
  { slug: "gitlab", name: "GitLab" },
  { slug: "github", name: "GitHub" },
  { slug: "atlassian", name: "Atlassian" },
  { slug: "asana", name: "Asana" },
  { slug: "monday", name: "Monday" },
  { slug: "miro", name: "Miro (alt)" },
  { slug: "hopin", name: "Hopin (alt)" },
  { slug: "klaviyo", name: "Klaviyo" },
  { slug: "hubspot", name: "HubSpot" },
  { slug: "zendesk", name: "Zendesk" },
  { slug: "intercom", name: "Intercom (alt)" },
  { slug: "automattic", name: "Automattic" },
  { slug: "wordpress", name: "WordPress.com" },
  { slug: "stripe", name: "Stripe (extra)" },
  { slug: "ftxapp", name: "Future" },
  { slug: "wisepay", name: "Wise" },
  { slug: "alephholding", name: "Aleph" },
  { slug: "monzo", name: "Monzo" },
  { slug: "starlingbank", name: "Starling Bank" },
  { slug: "klarna", name: "Klarna" },
  { slug: "auth0", name: "Auth0" },
  { slug: "okta", name: "Okta" },
  { slug: "cloudflare", name: "Cloudflare" },
  { slug: "1password", name: "1Password" },
  { slug: "lastpass", name: "LastPass" },
  { slug: "dropbox", name: "Dropbox" },
  { slug: "box", name: "Box" },
  { slug: "gusto", name: "Gusto" },
  { slug: "lattice", name: "Lattice" },
  { slug: "carta", name: "Carta" },
  { slug: "alma", name: "Alma" },
  { slug: "vinted", name: "Vinted" },
  { slug: "skyscanner", name: "Skyscanner" },
  { slug: "deliveroo", name: "Deliveroo" },
  { slug: "justeat", name: "Just Eat" },
  { slug: "justeattakeaway", name: "Just Eat Takeaway" },
  { slug: "trivago", name: "Trivago" },
  { slug: "expedia", name: "Expedia" },
  { slug: "booking", name: "Booking.com" },
  { slug: "kayak", name: "KAYAK" },
  { slug: "omio", name: "Omio" },
  { slug: "flixbus", name: "FlixBus" },
  { slug: "agodahotels", name: "Agoda" },
  { slug: "thefork", name: "TheFork" },
  { slug: "uberinternal", name: "Uber" },
  { slug: "lyft", name: "Lyft" },
  { slug: "instacart", name: "Instacart" },
  { slug: "doordash", name: "DoorDash" },
  { slug: "rappi", name: "Rappi" },
  // Italia tech + media
  { slug: "deltaelectronics", name: "Delta Electronics IT" },
  { slug: "subitospa", name: "Subito" },
  { slug: "immobiliarestaff", name: "Immobiliare.it" },
  { slug: "infojobs", name: "InfoJobs IT" },
  { slug: "depop", name: "Depop" },
  { slug: "bumble", name: "Bumble" },
  { slug: "matchgroup", name: "Match Group" },
  { slug: "bendingspoonsexp", name: "Bending Spoons (alt)" },
  { slug: "n26-bank", name: "N26 (alt)" },
  { slug: "qontoit", name: "Qonto Italia" },
  { slug: "satispayspa", name: "Satispay (alt)" },
  { slug: "casavoreal", name: "Casavo (alt)" },
  { slug: "moneyfarmuk", name: "MoneyFarm UK" },
  { slug: "talentgardenmilano", name: "Talent Garden (alt)" },
  { slug: "iconpicasso", name: "Iconpicasso" },
  // Design / Product agencies
  { slug: "frog", name: "Frog Design" },
  { slug: "ideo", name: "IDEO" },
  { slug: "huge", name: "Huge" },
  { slug: "rga", name: "R/GA" },
  { slug: "wundermanthompson", name: "Wunderman Thompson" },
];

export const LEVER_COMPANIES: AtsCompany[] = [
  { slug: "mollie", name: "Mollie", country: "NL" },
  { slug: "figma", name: "Figma" },
  { slug: "notion", name: "Notion" }, // fallback se notion passa anche qui
  { slug: "linear", name: "Linear" },
  { slug: "vercel", name: "Vercel" },
  { slug: "supabase", name: "Supabase" },
  { slug: "posthog", name: "PostHog" },
  { slug: "calcom", name: "Cal.com" },
  { slug: "resend", name: "Resend" },
  { slug: "ramp", name: "Ramp" },
  { slug: "anthropic", name: "Anthropic" },
  { slug: "openai", name: "OpenAI" },
  { slug: "plaid", name: "Plaid" },
  { slug: "bolt", name: "Bolt", country: "EE" },
  { slug: "pleo", name: "Pleo", country: "DK" },
  { slug: "trade-republic", name: "Trade Republic", country: "DE" },
  { slug: "homa-games", name: "Homa", country: "FR" },
  { slug: "aircall", name: "Aircall", country: "FR" },
  { slug: "frontify", name: "Frontify", country: "CH" },
  { slug: "onfido", name: "Onfido", country: "UK" },
  { slug: "stint", name: "Stint" },
  { slug: "amplitude", name: "Amplitude" },
  { slug: "loom", name: "Loom" },
  { slug: "attest", name: "Attest" },
  { slug: "checkout", name: "Checkout.com" },
  { slug: "getquin", name: "getquin" },
  // Italia / EU fintech + tech — expand for Milano/Roma pool
  { slug: "cherry", name: "Cherry Ventures" },
  { slug: "tomtom", name: "TomTom" },
  { slug: "contentsquare", name: "ContentSquare", country: "FR" },
  { slug: "factorial", name: "Factorial HR", country: "ES" },
  { slug: "spendesk", name: "Spendesk", country: "FR" },
  { slug: "welcometothejungle", name: "Welcome to the Jungle", country: "FR" },
  { slug: "openclassrooms", name: "OpenClassrooms", country: "FR" },
  { slug: "glovo", name: "Glovo" },
  { slug: "cabify", name: "Cabify" },
  { slug: "truelayer", name: "TrueLayer" },
  { slug: "zego", name: "Zego" },
  { slug: "ondato", name: "Ondato" },
  { slug: "zeplin", name: "Zeplin" },
  { slug: "happeo", name: "Happeo" },
  { slug: "tractian", name: "Tractian" },
  { slug: "dott", name: "Dott", country: "NL" },
  // Lever — tech + AI scaleup
  { slug: "huggingface", name: "Hugging Face" },
  { slug: "scale", name: "Scale AI" },
  { slug: "writer", name: "Writer" },
  { slug: "perplexity", name: "Perplexity" },
  { slug: "groq", name: "Groq" },
  { slug: "mistral", name: "Mistral" },
  { slug: "elevenlabs", name: "ElevenLabs" },
  { slug: "runway", name: "Runway" },
  { slug: "midjourney", name: "Midjourney" },
  { slug: "characterai", name: "Character AI" },
  { slug: "replit", name: "Replit" },
  { slug: "cursor", name: "Cursor" },
  { slug: "warp", name: "Warp" },
  { slug: "raycast", name: "Raycast" },
  { slug: "arc", name: "Arc Browser" },
  { slug: "browserbase", name: "Browserbase" },
  { slug: "linktree", name: "Linktree" },
  { slug: "calendly", name: "Calendly" },
  { slug: "loom-app", name: "Loom (alt)" },
  { slug: "figma-app", name: "Figma (alt)" },
  { slug: "framer", name: "Framer" },
  { slug: "webflow", name: "Webflow" },
  { slug: "canva-app", name: "Canva (alt)" },
  { slug: "vimeo", name: "Vimeo" },
  { slug: "tiktok", name: "TikTok" },
  { slug: "snapinc", name: "Snap" },
  { slug: "redditcareers", name: "Reddit" },
  { slug: "discordapp", name: "Discord" },
  { slug: "zoom", name: "Zoom" },
  { slug: "slack", name: "Slack" },
  { slug: "stripe-lever", name: "Stripe Lever" },
  { slug: "robinhood", name: "Robinhood" },
  { slug: "coinbase", name: "Coinbase" },
  { slug: "binance", name: "Binance" },
  { slug: "kraken", name: "Kraken" },
  { slug: "ledger", name: "Ledger" },
  // Italy/EU consumer + media
  { slug: "yousign", name: "Yousign" },
  { slug: "swile", name: "Swile" },
  { slug: "sorare", name: "Sorare" },
  { slug: "hellofresh", name: "HelloFresh" },
  { slug: "marleyspoon", name: "Marley Spoon" },
  { slug: "gorillas", name: "Gorillas" },
  { slug: "flink", name: "Flink" },
  { slug: "getir", name: "Getir" },
  { slug: "cazoo", name: "Cazoo" },
  { slug: "auto1", name: "Auto1" },
];

/**
 * Ashby (`jobs.ashbyhq.com/<slug>`). Tante startup tech moderne, YC, AI.
 * Slug = primo segmento del path su jobs.ashbyhq.com.
 */
export const ASHBY_COMPANIES: AtsCompany[] = [
  // Vercel ecosystem & dev-tools
  { slug: "vercel", name: "Vercel" },
  { slug: "linear", name: "Linear" },
  { slug: "ramp", name: "Ramp" },
  { slug: "posthog", name: "PostHog" },
  { slug: "replicate", name: "Replicate" },
  { slug: "modal", name: "Modal" },
  { slug: "neon", name: "Neon" },
  { slug: "railway", name: "Railway" },
  { slug: "supabase", name: "Supabase" },
  { slug: "browserbase", name: "Browserbase" },
  { slug: "resend", name: "Resend" },
  { slug: "trigger", name: "Trigger.dev" },
  { slug: "inngest", name: "Inngest" },
  { slug: "warp", name: "Warp" },
  { slug: "cursor", name: "Cursor" },
  { slug: "windsurf", name: "Windsurf" },
  { slug: "raycast", name: "Raycast" },
  // AI labs
  { slug: "openai", name: "OpenAI" },
  { slug: "anthropic", name: "Anthropic" },
  { slug: "perplexity", name: "Perplexity" },
  { slug: "huggingface", name: "Hugging Face" },
  { slug: "mistral", name: "Mistral AI" },
  { slug: "cohere", name: "Cohere" },
  { slug: "elevenlabs", name: "ElevenLabs" },
  { slug: "runway", name: "Runway" },
  { slug: "midjourney", name: "Midjourney" },
  { slug: "scale", name: "Scale AI" },
  { slug: "weights-and-biases", name: "Weights & Biases" },
  // Fintech
  { slug: "mercury", name: "Mercury" },
  { slug: "brex", name: "Brex" },
  { slug: "wise", name: "Wise" },
  { slug: "revolut", name: "Revolut" },
  { slug: "monzo", name: "Monzo" },
  { slug: "starlingbank", name: "Starling Bank" },
  { slug: "n26", name: "N26" },
  { slug: "qonto", name: "Qonto" },
  { slug: "tide", name: "Tide" },
  // SaaS / Productivity
  { slug: "notion", name: "Notion" },
  { slug: "figma", name: "Figma" },
  { slug: "loom", name: "Loom" },
  { slug: "airtable", name: "Airtable" },
  { slug: "miro", name: "Miro" },
  { slug: "clickup", name: "ClickUp" },
  { slug: "retool", name: "Retool" },
  { slug: "deel", name: "Deel" },
  { slug: "rippling", name: "Rippling" },
  { slug: "gusto", name: "Gusto" },
  { slug: "lattice", name: "Lattice" },
  // EU startup
  { slug: "doctolib", name: "Doctolib", country: "FR" },
  { slug: "alma", name: "Alma", country: "FR" },
  { slug: "swan", name: "Swan", country: "FR" },
  { slug: "spendesk", name: "Spendesk", country: "FR" },
  { slug: "tabby", name: "Tabby" },
  { slug: "tamara", name: "Tamara" },
  // Italian tech (alcuni adottano Ashby)
  { slug: "young-platform", name: "Young Platform", country: "IT" },
  { slug: "satispay", name: "Satispay", country: "IT" },
];

/**
 * SmartRecruiters (`jobs.smartrecruiters.com/<companyId>`). Enterprise EU,
 * tantissime aziende tradizionali. companyId è case-sensitive.
 */
export const SMARTRECRUITERS_COMPANIES: AtsCompany[] = [
  // Enterprise EU big
  { slug: "BoschGroup", name: "Bosch", country: "DE" },
  { slug: "Visa", name: "Visa" },
  { slug: "PublicisGroupe", name: "Publicis Groupe", country: "FR" },
  { slug: "IKEA", name: "IKEA", country: "SE" },
  { slug: "McDonalds", name: "McDonald's" },
  { slug: "SocieteGenerale", name: "Société Générale", country: "FR" },
  { slug: "Allianz", name: "Allianz", country: "DE" },
  { slug: "DeutscheBank", name: "Deutsche Bank", country: "DE" },
  { slug: "ING", name: "ING", country: "NL" },
  { slug: "Atos", name: "Atos", country: "FR" },
  { slug: "Capgemini", name: "Capgemini", country: "FR" },
  { slug: "Accenture", name: "Accenture" },
  { slug: "DeloitteUK", name: "Deloitte UK", country: "UK" },
  { slug: "PwC", name: "PwC" },
  { slug: "Equinix", name: "Equinix" },
  { slug: "Ubisoft", name: "Ubisoft", country: "FR" },
  { slug: "TVH", name: "TVH", country: "BE" },
  { slug: "BalfourBeatty", name: "Balfour Beatty", country: "UK" },
  { slug: "Skanska", name: "Skanska", country: "SE" },
  { slug: "Heineken", name: "Heineken", country: "NL" },
  { slug: "DanoneAG", name: "Danone", country: "FR" },
  { slug: "Nestle", name: "Nestlé", country: "CH" },
  { slug: "L'Oreal", name: "L'Oréal", country: "FR" },
  { slug: "Pirelli", name: "Pirelli", country: "IT" },
  { slug: "Generali", name: "Generali", country: "IT" },
  { slug: "Eni", name: "Eni", country: "IT" },
  { slug: "TIM", name: "TIM", country: "IT" },
  { slug: "Vodafone", name: "Vodafone" },
  { slug: "Orange", name: "Orange", country: "FR" },
  // Tech & SaaS via SmartRecruiters
  { slug: "Twilio", name: "Twilio" },
  { slug: "Square", name: "Square" },
  { slug: "Compass", name: "Compass" },
  { slug: "Glassdoor", name: "Glassdoor" },
  { slug: "Booking", name: "Booking.com", country: "NL" },
  { slug: "GetYourGuide", name: "GetYourGuide", country: "DE" },
  { slug: "Skyscanner", name: "Skyscanner", country: "UK" },
  // Italian companies su SmartRecruiters
  { slug: "OVS", name: "OVS", country: "IT" },
  { slug: "Generali1", name: "Generali (alt)", country: "IT" },
  { slug: "UniCredit", name: "UniCredit", country: "IT" },
  { slug: "IntesaSanpaolo", name: "Intesa Sanpaolo", country: "IT" },
];
